name: NearMe
options:
  bundleIdPrefix: com.nearme
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "16.3"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    version: 1.19.0
  CombineMoya:
    url: https://github.com/Moya/Moya.git
    version: 15.0.3
  SwiftLocation:
    url: https://github.com/malcommac/SwiftLocation.git
    branch: master
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    version: 20.0.2
targets:
  NearMeApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: ComposableArchitecture
      - package: CombineMoya
      - package: SwiftLocation
    info:
      path: Sources/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
        NSLocationWhenInUseUsageDescription: TODO
        NSLocationAlwaysUsageDescription: TODO
        NSLocationAlwaysAndWhenInUseUsageDescription: TODO
    preBuildScripts:
      - script: "mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 6.0"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
  NearMeAppTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: NearMeApp
    info:
      path: Tests/Info.plist
